### ISSUE TITLE
Error: reference to member 'v11_1' cannot be resolved without a contextual type.macOS(.v11_1)

### ISSUE THREAD

**Issue by VarshaBhatiaPapershift** [mxcl/swift-sh#142] opened 2021-01-15 08:17 UTC
The script doesn't run in macOS Big Sur Version 11.1 
Getting the below error: 

<img width="1708" alt="Screenshot 2021-01-15 at 1 38 36 PM" src="https://user-images.githubusercontent.com/66675194/104698234-10b44700-5737-11eb-8b80-1a2cbe9e6873.png">

<img width="571" alt="Screenshot 2021-01-15 at 1 47 01 PM" src="https://user-images.githubusercontent.com/66675194/104699090-39890c00-5738-11eb-928f-f79ab51d42e7.png">

The workaround I found is to either remove or comment out the below code:

```
#if swift(>=5) && os(macOS)
pkg.platforms = [
   .macOS(.v11_1)
]
#endif
```

**Comment by Jeehut** [comment] 2021-01-16 09:25
I just provided a fix for this issue in #143.

Install my fix before it's merged by running:
```bash
brew uninstall --ignore-dependencies swift-sh
brew install mint
mint install Jeehut/swift-sh@master
```

Once a proper fix is released, go back to original swift-sh by running:
```bash
mint uninstall Jeehut/swift-sh
brew install swift-sh
```

**Comment by mxcl** [comment] 2021-05-25 17:01
I cannot reproduce this, can someone provide a script that does? Otherwise I don’t see how I can fix it.

I run Big Sur.

**Comment by mxcl** [comment] 2021-05-25 22:37
Try 2.3.0, reopen if not fixed.

**Closed by mxcl** 2021-05-25 22:37 UTC
